### ISSUE TITLE
Please add k8s clusterRole and clusterRoleBinding to README

### ISSUE THREAD

**Issue by oernii** [FU-Solutions/zabbix_kubernetes_checks#2]
I've created a new readonly role:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-reader-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods","configmaps","services","events","namespaces","nodes","limitranges","persistentvolumes","persistenttvolumeclaims","resourcequotas"]
  verbs: ["get", "watch", "list"]
- apiGroups:
    - apps
  resources: ["*"]
  verbs:
    - get
    - list
    - watch
```

and binded it to the zabbix SA:
` create clusterrolebinding kube-support-kube-reader --clusterrole=kube-reader-cluster-role --serviceaccount=kube-system:zbx`
